FROM node:15.5.0-alpine3.11

# Accessing the webapp
EXPOSE 3000
# Necessary to enable hot reloading
EXPOSE 35729

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# Copy sources
COPY package.json .
COPY package-lock.json .

RUN npm install
RUN npm install react-scripts -g

ADD . /app

CMD ["npm", "start"]
