"""users

Revision ID: 5366d9a8a894
Revises: 
Create Date: 2020-12-26 18:46:06.889284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import PasswordType, Password

# revision identifiers, used by Alembic.
revision = '5366d9a8a894'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=64), nullable=False),
                    sa.Column('password', PasswordType(schemes=['pbkdf2_sha512']), nullable=False),
                    sa.Column('firstname', sa.String(length=128), nullable=True),
                    sa.Column('lastname', sa.String(length=128), nullable=True),
                    sa.Column('email', sa.String(length=256), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )
    # ### end Alembic commands ###

    # Add admin user with basic
    # TODO Modify it after first run
    user_table = sa.table('user',
                          sa.column("password", PasswordType(schemes=['pbkdf2_sha512'])),
                          sa.column("username", sa.String)
                          )

    data = [{
        "username": "admin",
        "password": Password("admin")
    }]

    op.bulk_insert(user_table, data)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
